version: "3.8"

services:
  # Backend Service
  app:
    build: ./backend
    container_name: fastapi_insurance_dev
    ports:
      - "9000:9000"
    expose:
      - 9000
    command: uv run uvicorn main:app --port 9000 --host 0.0.0.0
    environment:
      DATABASE_URL: postgresql://postgresAldin:aldinIzCarobneLampe@db:5433/postgresDB
      DATABASE_HOST: db
      DATABASE_PORT: 5433
        - WATCHFILES_FORCE_POLLING=true
    restart: always

  # Database Service
  db:
    image: postgres:15-alpine
    container_name: insurance_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgresAldin
      POSTGRES_PASSWORD: aldinIzCarobneLampe
      POSTGRES_DB: postgresDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5433
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresAldin -d postgresDB"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -p 5433
volumes:
  postgres_data:
